# Generated by Django 4.2.3 on 2023-07-25 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_etiqueta_noticia_alter_categoria_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Etiqueta',
        ),
        migrations.AlterModelOptions(
            name='categoria',
            options={},
        ),
        migrations.RemoveField(
            model_name='categoria',
            name='activo',
        ),
        migrations.RemoveField(
            model_name='categoria',
            name='actualizacion',
        ),
        migrations.RemoveField(
            model_name='categoria',
            name='creacion',
        ),
        migrations.RemoveField(
            model_name='noticia',
            name='autor',
        ),
        migrations.AddField(
            model_name='noticia',
            name='categorias',
            field=models.ManyToManyField(related_name='noticias', to='posts.categoria'),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='fecha_publicacion',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
