# Generated by Django 4.2.3 on 2023-08-01 13:14

import apps.posts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_noticia_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to=apps.posts.models.nombre_archivo_incluye_extension),
        ),
    ]
