# Generated by Django 4.2.3 on 2023-08-01 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_noticia_autor_alter_noticia_imagen'),
    ]

    operations = [
        migrations.CreateModel(
            name='Etiqueta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='noticia',
            name='etiquetas',
            field=models.ManyToManyField(to='posts.etiqueta'),
        ),
    ]
