# Generated by Django 4.2.3 on 2023-08-02 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_comentario'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentario',
            name='autor',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
